<?php
/**
 * Installation State & Engine Helper
 * Loan Management System (loan-mgt) - Phase 9
 */

if (!defined('ROOT_PATH')) {
    define('ROOT_PATH', dirname(__DIR__));
}

if (!defined('INSTALL_LOCK_FILE')) {
    define('INSTALL_LOCK_FILE', ROOT_PATH . DIRECTORY_SEPARATOR . 'config' . DIRECTORY_SEPARATOR . 'installed.lock');
}

/**
 * Escapes HTML output securely.
 *
 * @param mixed $value
 * @return string
 */
if (!function_exists('e')) {
    function e($value): string
    {
        return htmlspecialchars((string)($value ?? ''), ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
    }
}

/**
 * Checks whether the application installation has been completed.
 *
 * @return bool
 */
function is_installed(): bool
{
    return file_exists(INSTALL_LOCK_FILE);
}

/**
 * Enforces that the application is installed. Redirects to installer if not.
 *
 * @return void
 */
function require_installed(): void
{
    if (!is_installed()) {
        // Calculate dynamic relative/absolute path to installer
        $installerUrl = get_installer_base_url() . '/index.php';
        header('Location: ' . $installerUrl);
        exit;
    }
}

/**
 * Enforces that the application is NOT installed. Redirects to locked screen if already installed.
 *
 * @return void
 */
function require_not_installed(): void
{
    if (is_installed()) {
        $lockUrl = get_installer_base_url() . '/lock.php';
        header('Location: ' . $lockUrl);
        exit;
    }
}

/**
 * Helper to determine base URL for installer directory.
 *
 * @return string
 */
function get_installer_base_url(): string
{
    return rtrim(get_app_base_url(), '/') . '/installer';
}

/**
 * Helper to determine root application base URL.
 *
 * @return string
 */
function get_app_base_url(): string
{
    if (isset($_SERVER['HTTP_HOST'])) {
        $isHttps = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') || (isset($_SERVER['SERVER_PORT']) && $_SERVER['SERVER_PORT'] == 443);
        $protocol = $isHttps ? 'https://' : 'http://';
        $host = $_SERVER['HTTP_HOST'];
        
        $docRoot = str_replace('\\', '/', realpath($_SERVER['DOCUMENT_ROOT'] ?? '') ?: ($_SERVER['DOCUMENT_ROOT'] ?? ''));
        $appRoot = str_replace('\\', '/', realpath(ROOT_PATH) ?: ROOT_PATH);
        
        if (!empty($docRoot) && stripos($appRoot, $docRoot) === 0) {
            $subDir = substr($appRoot, strlen($docRoot));
        } else {
            $scriptDir = str_replace('\\', '/', dirname($_SERVER['SCRIPT_NAME'] ?? ''));
            $subDir = preg_replace('#/installer.*$#i', '', $scriptDir);
        }
        
        $subDir = trim((string)$subDir, '/');
        $basePath = !empty($subDir) ? '/' . $subDir : '';
        
        return rtrim($protocol . $host . $basePath, '/');
    }
    return 'http://localhost/loan-mgt';
}

/**
 * Generates an installer-specific CSRF token.
 *
 * @return string
 */
function installer_csrf_token(): string
{
    if (session_status() === PHP_SESSION_NONE) {
        @session_start();
    }
    if (empty($_SESSION['_installer_csrf_token'])) {
        $_SESSION['_installer_csrf_token'] = bin2hex(random_bytes(32));
    }
    return $_SESSION['_installer_csrf_token'];
}

/**
 * Validates the installer CSRF token from POST request.
 *
 * @return bool
 */
function verify_installer_csrf_token(): bool
{
    if (session_status() === PHP_SESSION_NONE) {
        @session_start();
    }
    $submittedToken = $_POST['csrf_token'] ?? '';
    $sessionToken   = $_SESSION['_installer_csrf_token'] ?? '';

    if (empty($submittedToken) || empty($sessionToken)) {
        return false;
    }
    return hash_equals($sessionToken, $submittedToken);
}

/**
 * Safely writes config/database.php with PHP string escaping.
 *
 * @param string $host
 * @param string $name
 * @param string $user
 * @param string $pass
 * @param string $port
 * @return bool
 */
function generate_database_config(string $host, string $name, string $user, string $pass, string $port = '3306'): bool
{
    $configFile = ROOT_PATH . DIRECTORY_SEPARATOR . 'config' . DIRECTORY_SEPARATOR . 'database.php';
    $configDir  = dirname($configFile);

    if (!is_dir($configDir) || !is_writable($configDir)) {
        return false;
    }

    $escapedHost = var_export($host, true);
    $escapedPort = var_export($port ?: '3306', true);
    $escapedName = var_export($name, true);
    $escapedUser = var_export($user, true);
    $escapedPass = var_export($pass, true);

    $content = "<?php\n" .
        "/**\n" .
        " * Database Configuration & PDO Connection\n" .
        " * Loan Management System (loan-mgt)\n" .
        " * Auto-generated by Production Installer\n" .
        " */\n\n" .
        "if (!defined('DB_HOST')) {\n" .
        "    define('DB_HOST', {$escapedHost});\n" .
        "    define('DB_PORT', {$escapedPort});\n" .
        "    define('DB_NAME', {$escapedName});\n" .
        "    define('DB_USER', {$escapedUser});\n" .
        "    define('DB_PASS', {$escapedPass});\n" .
        "    define('DB_CHARSET', 'utf8mb4');\n" .
        "}\n\n" .
        "/**\n" .
        " * Get the centralized PDO database connection instance.\n" .
        " *\n" .
        " * @return PDO\n" .
        " */\n" .
        "function get_db_connection(): PDO\n" .
        "{\n" .
        "    static \$pdo = null;\n\n" .
        "    if (\$pdo === null) {\n" .
        "        \$dsn = sprintf(\n" .
        "            'mysql:host=%s;port=%s;dbname=%s;charset=%s',\n" .
        "            DB_HOST,\n" .
        "            DB_PORT,\n" .
        "            DB_NAME,\n" .
        "            DB_CHARSET\n" .
        "        );\n\n" .
        "        \$options = [\n" .
        "            PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,\n" .
        "            PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,\n" .
        "            PDO::ATTR_EMULATE_PREPARES   => false,\n" .
        "            PDO::MYSQL_ATTR_INIT_COMMAND => \"SET NAMES \" . DB_CHARSET . \" COLLATE utf8mb4_unicode_ci\",\n" .
        "        ];\n\n" .
        "        try {\n" .
        "            \$pdo = new PDO(\$dsn, DB_USER, DB_PASS, \$options);\n" .
        "        } catch (PDOException \$e) {\n" .
        "            error_log('Database Connection Error: ' . \$e->getMessage());\n\n" .
        "            if (defined('APP_ENV') && APP_ENV === 'development' && php_sapi_name() === 'cli') {\n" .
        "                throw new PDOException('Database connection failed: ' . \$e->getMessage());\n" .
        "            }\n\n" .
        "            http_response_code(500);\n" .
        "            die(\n" .
        "                '<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"utf-8\"><title>Service Unavailable</title>' .\n" .
        "                '<style>body{font-family:system-ui,-apple-system,sans-serif;display:flex;align-items:center;justify-content:center;height:100vh;margin:0;background:#f8fafc;color:#1e293b;}' .\n" .
        "                '.card{background:#fff;border:1px solid #e2e8f0;padding:2rem;border-radius:8px;max-width:500px;text-align:center;box-shadow:0 4px 6px -1px rgba(0,0,0,0.1);}' .\n" .
        "                'h1{font-size:1.25rem;margin:0 0 0.5rem;color:#0f172a;}p{color:#64748b;margin:0;line-height:1.5;}</style></head>' .\n" .
        "                '<body><div class=\"card\"><h1>Database Connection Error</h1><p>Unable to connect to the database service. Please verify that MySQL is running and the database is configured properly.</p></div></body></html>'\n" .
        "            );\n" .
        "        }\n" .
        "    }\n\n" .
        "    return \$pdo;\n" .
        "}\n\n" .
        "\$pdo = get_db_connection();\n";

    return (file_put_contents($configFile, $content, LOCK_EX) !== false);
}

/**
 * Creates the installation lock file.
 *
 * @param array $metadata
 * @return bool
 */
function create_installation_lock(array $metadata = []): bool
{
    $lockData = array_merge([
        'installed_at' => date('c'),
        'version'      => '9.0.0',
        'status'       => 'locked'
    ], $metadata);

    // Filter out any accidental credential fields
    unset($lockData['db_password'], $lockData['password'], $lockData['admin_password']);

    $content = json_encode($lockData, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
    return (file_put_contents(INSTALL_LOCK_FILE, $content, LOCK_EX) !== false);
}

/**
 * Parses and executes a multi-statement SQL script using PDO.
 * Properly handles comments (-- , #, /* * /), quoted strings, and multi-line statements.
 *
 * @param PDO $pdo
 * @param string $sqlContent
 * @return array ['success' => bool, 'statements_executed' => int, 'error' => string|null]
 */
function run_sql_import(PDO $pdo, string $sqlContent): array
{
    $statements = [];
    $buffer = '';
    $inSingleQuote = false;
    $inDoubleQuote = false;
    $inBacktick = false;
    $len = strlen($sqlContent);
    $i = 0;

    while ($i < $len) {
        $char = $sqlContent[$i];
        $next = ($i + 1 < $len) ? $sqlContent[$i + 1] : '';

        // Check for comment starts if not inside quotes
        if (!$inSingleQuote && !$inDoubleQuote && !$inBacktick) {
            // Multi-line comment /* ... */
            if ($char === '/' && $next === '*') {
                $closePos = strpos($sqlContent, '*/', $i + 2);
                if ($closePos === false) {
                    $i = $len; // Unclosed comment till EOF
                } else {
                    $i = $closePos + 2;
                }
                continue;
            }

            // Single line comment -- or #
            if (($char === '-' && $next === '-') || $char === '#') {
                $nlPos = strpos($sqlContent, "\n", $i);
                if ($nlPos === false) {
                    $i = $len;
                } else {
                    $i = $nlPos + 1;
                }
                continue;
            }
        }

        // Handle quotes
        if ($char === "'" && !$inDoubleQuote && !$inBacktick) {
            if ($inSingleQuote) {
                // Check if escaped with \' or ''
                $prev = ($i > 0) ? $sqlContent[$i - 1] : '';
                if ($prev !== '\\') {
                    $inSingleQuote = false;
                }
            } else {
                $inSingleQuote = true;
            }
        } elseif ($char === '"' && !$inSingleQuote && !$inBacktick) {
            if ($inDoubleQuote) {
                $prev = ($i > 0) ? $sqlContent[$i - 1] : '';
                if ($prev !== '\\') {
                    $inDoubleQuote = false;
                }
            } else {
                $inDoubleQuote = true;
            }
        } elseif ($char === '`' && !$inSingleQuote && !$inDoubleQuote) {
            $inBacktick = !$inBacktick;
        }

        // Check for statement terminator ';'
        if ($char === ';' && !$inSingleQuote && !$inDoubleQuote && !$inBacktick) {
            $stmt = trim($buffer);
            if (!empty($stmt)) {
                $statements[] = $stmt;
            }
            $buffer = '';
            $i++;
            continue;
        }

        $buffer .= $char;
        $i++;
    }

    $lastStmt = trim($buffer);
    if (!empty($lastStmt)) {
        $statements[] = $lastStmt;
    }

    $count = 0;
    foreach ($statements as $stmt) {
        if (empty($stmt)) {
            continue;
        }
        try {
            $pdo->exec($stmt);
            $count++;
        } catch (PDOException $e) {
            return [
                'success'             => false,
                'statements_executed' => $count,
                'error'               => 'SQL execution error: ' . $e->getMessage(),
                'statement'           => mb_substr($stmt, 0, 150) . '...'
            ];
        }
    }

    return [
        'success'             => true,
        'statements_executed' => $count,
        'error'               => null
    ];
}
